update

diff --git a/include/global_functions b/include/global_functions
--- a/include/global_functions
+++ b/include/global_functions
@@ -101,11 +101,54 @@ function prevent_sudo_or_root() {
 	esac
 }
 
+# ------------------------------------- #
+# Function Check if pacman is available #
+# ------------------------------------- #
+# check if the pacman package manager is available on the system.
+# If pacman is not found, it prints an error message indicating that
+# the system is not Arch Linux or an Arch-based distribution,
+# and then it exits the script with a status code of 1.
+check_pacman() {
+	if ! command -v pacman >/dev/null 2>&1; then
+		printf "\e[31m[$0]: pacman not found, it seems that the system is not ArchLinux or Arch-based distros. Aborting...\e[0m\n"
+		exit 1
+	fi
+	echo "pacman is found. Continuing with the script..."
+}
+
 # Function to check if yay is installed
 check_yay() {
 	if ! command -v yay &>/dev/null; then
 		echo "yay is not installed. Please install yay and try again."
 		exit 1
+	fi
+}
+# Function to check if yay is installed and install it if not
+check_yay() {
+	if ! command -v yay &>/dev/null; then
+		echo "yay is not installed. Installing yay..."
+
+		# Install yay
+		sudo pacman -S --needed base-devel git
+
+		# Clone the yay repository from the AUR
+		git clone https://aur.archlinux.org/yay.git
+
+		# Change directory to yay
+		cd yay
+
+		# Build and install yay
+		makepkg -si
+
+		# Change back to the previous directory
+		cd ..
+
+		# Remove the yay directory
+		rm -rf yay
+
+		echo "yay has been successfully installed."
+	else
+		echo "yay is already installed."
 	fi
 }
 
@@ -116,4 +159,16 @@ confirm() {
 		echo "Action cancelled."
 		exit 1
 	fi
+}
+
+# ------------------- #
+# Update the Packages #
+# ------------------- #
+update_packages() {
+	echo 'Update the Packages'
+	sudo rm /var/lib/pacman/db.lck
+	sudo pacman -Scc --noconfirm
+	sudo pacman -Syu --noconfirm && sudo pacman -Sc --noconfirm && yay -Syu --noconfirm --devel
+	sudo pacman -S --noconfirm linux-firmware
+	sudo mkinitcpio -P
 }
